MOCK_GET_INITIATOR_BY_ADDRESS = {
    "result": {
        "type": "ISCSI",
        "address": "iqn.1993-08.org.debian:01:515ccce1836",
        "host_id": 4273,
        "port_key": 6.917529027641082e18,
        "targets": [
            {
                "address": "iqn.2009-11.com.infinidat:storage:infinibox-sn-30051",
                "node_id": 1,
                "session_id": 9613344775,
            },
            {
                "address": "iqn.2009-11.com.infinidat:storage:infinibox-sn-30051",
                "node_id": 1,
                "session_id": 9613344776,
            },
        ],
    },
    "error": None,
    "metadata": {"ready": True},
}

MOCK_GET_COMPONENTS = {
    "result": {
        "enclosures": [],
        "nodes": [
            {
                "model": "Node VM",
                "vendor": "VMWare",
                "firmware": "",
                "id": 1,
                "state": "ACTIVE",
                "state_description": None,
                "name": "node-1",
                "node_bbu_protection": "N/A",
                "protecting_bbu": 0,
                "protecting_bbu_charge_level": -1,
                "ipmi.state": None,
                "ntp.state_description": "",
                "ntp.state": "OK",
                "bios.state_description": None,
                "bios.state": None,
                "services": [
                    {
                        "name": "core",
                        "role": "MASTER",
                        "state": "ACTIVE",
                        "state_description": None,
                        "number_of_respawns": 0,
                        "respawns": 0,
                        "processes_up": 0,
                    },
                    {
                        "name": "nas",
                        "role": "MASTER",
                        "state": "ACTIVE",
                        "state_description": None,
                        "number_of_respawns": 0,
                        "respawns": 0,
                        "processes_up": 0,
                    },
                    {
                        "name": "iscsi",
                        "role": "MASTER",
                        "state": "ACTIVE",
                        "state_description": None,
                        "number_of_respawns": 0,
                        "respawns": 0,
                        "processes_up": 0,
                    },
                    {
                        "name": "mgmt",
                        "role": "MASTER",
                        "state": "ACTIVE",
                        "state_description": "N/A",
                        "number_of_respawns": 0,
                        "respawns": 0,
                        "processes_up": 0,
                    },
                    {
                        "name": "replication",
                        "role": "MASTER",
                        "state": "ACTIVE",
                        "state_description": None,
                        "number_of_respawns": 0,
                        "respawns": 0,
                        "processes_up": 0,
                    },
                    {
                        "name": "san",
                        "role": "MASTER",
                        "state": "ACTIVE",
                        "state_description": None,
                        "number_of_respawns": 0,
                        "respawns": 0,
                        "processes_up": 0,
                    },
                ],
                "fc_ports": [],
                "drives": [
                    {
                        "model": "Virtual disk",
                        "vendor": "VMware",
                        "firmware": "unknown",
                        "state": "OK",
                        "id": 1,
                        "state_description": "",
                        "serial_number": "unknown",
                        "drive_index": 1,
                        "node_index": 1,
                        "type": "Disk",
                        "wearout": None,
                        "probe_ttl": 1600000,
                        "last_probe_timestamp": 1739199243000,
                    }
                ],
                "tpm": {
                    "model": None,
                    "vendor": None,
                    "firmware": None,
                    "state": "UNSUPPORTED",
                    "id": 1,
                    "state_description": "TPM is supported only with HBA330",
                    "node_index": 1,
                    "probe_ttl": 600000,
                    "last_probe_timestamp": 1739199169000,
                },
                "eth_ports": [
                    {
                        "model": "82545EM Gigabit Ethernet Controller (Copper)",
                        "vendor": "Intel Corporation",
                        "firmware": "",
                        "state": "OK",
                        "name": "eth-mgmt",
                        "node_index": 1,
                        "state_description": "",
                        "id": 1,
                        "role": "MANAGEMENT",
                        "hw_addr": "00:50:56:97:1a:21",
                        "ip_v4_addr": "172.20.93.67",
                        "ip_v4_broadcast": "172.20.93.67",
                        "ip_v4_netmask": "255.255.224.0",
                        "ip_v6_addr": "fe80::250:56ff:fe97:1a21%eth-mgmt",
                        "ip_v6_netmask": "ffff:ffff:ffff:ffff::/64",
                        "connection_speed": 1000000000,
                        "port_number": 1,
                        "link_state": "UP",
                        "max_speed": 1000000000,
                        "media_type": "copper",
                        "sfp_type": None,
                        "sfp_model": None,
                        "laser_power_level_state": None,
                        "laser_power_level_state_description": None,
                        "laser_TX_power_mW": None,
                        "laser_RX_power_mW": None,
                        "RX_power_high_Warning_THLD_mW": None,
                        "RX_power_low_Warning_THLD_mW": None,
                        "TX_power_high_Warning_THLD_mW": None,
                        "TX_power_low_Warning_THLD_mW": None,
                        "SFP_Temperature_Deg_C": None,
                        "SFP_Voltage_Volt": None,
                        "SFP_Laser_Bias_Current_mA": None,
                        "system_interface_port_number": 1,
                        "probe_ttl": 10000,
                        "last_probe_timestamp": 1739199396000,
                    },
                    {
                        "model": "82545EM Gigabit Ethernet Controller (Copper)",
                        "vendor": "Intel Corporation",
                        "firmware": "",
                        "state": "OK",
                        "name": "eth-data1",
                        "node_index": 1,
                        "state_description": "",
                        "id": 2,
                        "role": "DATA",
                        "hw_addr": "00:50:56:97:0f:2d",
                        "ip_v4_addr": None,
                        "ip_v4_broadcast": None,
                        "ip_v4_netmask": None,
                        "ip_v6_addr": "fe80::250:56ff:fe97:f2d%eth-data1",
                        "ip_v6_netmask": "ffff:ffff:ffff:ffff::/64",
                        "connection_speed": 1000000000,
                        "port_number": 2,
                        "link_state": "UP",
                        "max_speed": 1000000000,
                        "media_type": "copper",
                        "sfp_type": None,
                        "sfp_model": None,
                        "laser_power_level_state": None,
                        "laser_power_level_state_description": None,
                        "laser_TX_power_mW": None,
                        "laser_RX_power_mW": None,
                        "RX_power_high_Warning_THLD_mW": None,
                        "RX_power_low_Warning_THLD_mW": None,
                        "TX_power_high_Warning_THLD_mW": None,
                        "TX_power_low_Warning_THLD_mW": None,
                        "SFP_Temperature_Deg_C": None,
                        "SFP_Voltage_Volt": None,
                        "SFP_Laser_Bias_Current_mA": None,
                        "system_interface_port_number": 2,
                        "probe_ttl": 10000,
                        "last_probe_timestamp": 1739199396000,
                    },
                    {
                        "model": "82545EM Gigabit Ethernet Controller (Copper)",
                        "vendor": "Intel Corporation",
                        "firmware": "",
                        "state": "OK",
                        "name": "eth-data2",
                        "node_index": 1,
                        "state_description": "",
                        "id": 3,
                        "role": "DATA",
                        "hw_addr": "00:50:56:97:a6:c5",
                        "ip_v4_addr": None,
                        "ip_v4_broadcast": None,
                        "ip_v4_netmask": None,
                        "ip_v6_addr": "fe80::250:56ff:fe97:a6c5%eth-data2",
                        "ip_v6_netmask": "ffff:ffff:ffff:ffff::/64",
                        "connection_speed": 1000000000,
                        "port_number": 3,
                        "link_state": "UP",
                        "max_speed": 1000000000,
                        "media_type": "copper",
                        "sfp_type": None,
                        "sfp_model": None,
                        "laser_power_level_state": None,
                        "laser_power_level_state_description": None,
                        "laser_TX_power_mW": None,
                        "laser_RX_power_mW": None,
                        "RX_power_high_Warning_THLD_mW": None,
                        "RX_power_low_Warning_THLD_mW": None,
                        "TX_power_high_Warning_THLD_mW": None,
                        "TX_power_low_Warning_THLD_mW": None,
                        "SFP_Temperature_Deg_C": None,
                        "SFP_Voltage_Volt": None,
                        "SFP_Laser_Bias_Current_mA": None,
                        "system_interface_port_number": 3,
                        "probe_ttl": 10000,
                        "last_probe_timestamp": 1739199396000,
                    },
                ],
                "ib_ports": [],
                "pgs": [
                    {
                        "model": "Port-Group Master with slaves: eth-data1",
                        "vendor": "unknown",
                        "firmware": "",
                        "state": "OK",
                        "name": "N1L1",
                        "node_index": 1,
                        "state_description": "",
                        "id": 1,
                        "role": "PG",
                        "hw_addr": "unknown",
                        "ip_v4_addr": None,
                        "ip_v4_broadcast": None,
                        "ip_v4_netmask": None,
                        "ip_v6_addr": "fe80::250:56ff:fe97:f2d%N1L1",
                        "ip_v6_netmask": "ffff:ffff:ffff:ffff::/64",
                        "connection_speed": 1000000000,
                        "system_interface_port_number": 1,
                        "probe_ttl": 10000,
                        "last_probe_timestamp": 1739199396000,
                    }
                ],
                "power_supplies": [],
                "power": 0,
                "hba": [],
                "connectivity_status": {
                    "enclosures": [],
                    "pdu": [],
                    "eth_switches": [],
                    "support_appliances": [],
                    "bbu": [],
                },
                "security": {
                    "node_id": "1",
                    "security_mode": "STANDARD",
                    "crypto_module": {
                        "state": "N/A",
                        "server_state": "N/A",
                        "version": "N/A",
                    },
                },
                "probe_ttl": 60000,
                "last_probe_timestamp": 0,
            }
        ],
        "rack": 1,
        "ups": [],
        "pdu_map_name": "",
        "eth_switches": [],
        "enclosures_number": 0,
        "patch_panels": [],
        "pdus": [],
    },
    "error": None,
    "metadata": {"ready": True},
}

MOCK_GET_INITIATOR_NOT_FOUND = {
    "result": None,
    "error": {
        "code": "INITIATOR_NOT_FOUND",
        "message": "Initiator not found",
        "reasons": [],
        "severity": "ERROR",
        "is_remote": False,
        "data": None,
    },
    "metadata": {"ready": True},
}
